### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by fordsfords** [wickerbox/Protoboard-DIP-for-CHIP#1]
Very minor doc issue.  In the readme.md, the link to the template is wrong.

https://github.com/wickerbox/wickerlib/tree/master/templates/chip-dip-shield

should presumably be changed to

https://github.com/wickerbox/wickerlib/tree/master/templates/chip-dip-2layer

P.S. - love the board!  I'll be getting some.

**Comment by wicker** [comment]
Nice catch! That'll teach me to reorganize the wickerlib template folder and forget to check my downstream repos that depend on it. I've pushed a fixed readme. Thanks! :)
